# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('countries', models.ManyToManyField(to='maps.Country')),
            ],
            options={
                'verbose_name_plural': 'Граждане',
                'verbose_name': 'Гражданин',
            },
        ),
    ]
