# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0002_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='resident',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
