# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170314_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='maps.Country'),
        ),
    ]
